
TARGET=spi_example

#includes
INC=-I../uart/include -I../spi/include -Iinclude

#list of libraries that will be used for linking
LIBS=libspi.a

#project specific dependencies
DEPS=

#library name
LIB_TARGET=

include ../common/common.mk

