
TARGET=cat25320_test

#includes
INC=-I../uart/include -I../spi/include

#list of libraries that will be used for linking
LIBS=libuart.a libspi.a

#project specific dependencies
DEPS=

#library name
LIB_TARGET=libcat25320.a

F_CPU=14745600UL

include ../common/common.mk

