
TARGET=uart_example

#includes
INC=-I../uart/

#list of libraries that will be used for linking
LIBS=

#project specific dependencies
DEPS=

#dependency objects for building library
LIB_DEPS=
#library name
LIB_TARGET=libuart.a

include ../common/common.mk

